config/routes.rb
Dash::Application.routes.draw do
  get "sessions/create"
  get "sessions/destroy"
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'login', to: 'users#login'

  root to: 'users#index'

  resources :sessions, only: [:create, :destroy]

  resources :users do
    collection do
      post :become_searchable
      post :find_opponent
      post :available_members
    end
  end

  resources :games do
    member do
      post :play
      post :ready
      post :action
      post :opponent_ready
      delete :play
    end
  end

  resources :players do
    member do
      post :action
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :players
  has_many :initiated_games, foreign_key: 'initiator_id', class_name: 'Game'
  has_many :opponent_games,  foreign_key: 'opponent_id',  class_name: 'Game'
  has_many :won_games,       foreign_key: 'winner_id',    class_name: 'Game'

  before_save :update_tier_preference

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def self.delete
    User.all.each(&:destroy)
  end

  def first_name
    name.split(" ").first
  end

  def games
    opponent_games.merge(initiated_games)
  end

  def self.valid_session_id?(session)
    session[:user_id] && User.find_by(id: session[:user_id]).present?
  end

  def snatch_opponent(tier)
    available_users = User.where(available: true, tier_preference: tier).where.not(id: id)
    opponent = available_users.shuffle.try(:first)
    return nil unless opponent
    opponent.update_attribute(:available, false)
    update_attribute(:available, false)
    opponent
  end

  def waiting_game
    opponent_games.where(opponent_ready: false).try(:first)
  end

  def self.delete_everything!
    [Action,Trap,BasePosition,Player,Game,User].each do |model|
      model.all.each(&:destroy)
    end
  end

  def date_played(user)
    games_with(user).try(:last).try(:updated_at)
  end

  def games_with(user)
    games.where(initiator: user) + games.where(opponent: user)
  end

  def transfer_money(loser, wager)
    give_money_to_winner(wager)
    take_money_from_loser(loser, wager)
  end

  def tier_options
    self.class.tier_options(money)
  end

  def self.tier_options(money)
    options = []
    i = 1

    while i <= money
      options << i
      i *= 2
    end

    options
  end

private

  def update_tier_preference
    if money_changed?
      if money_was > money || (money_was < money && had_highest_tier?)
        self.tier_preference = tier_options.last
      end
    end
  end

  def had_highest_tier?
    money_was >= self.class.tier_options(money_was).last
  end

  def give_money_to_winner(wager)
    new_amount = money + wager
    update_attribute(:money, new_amount)
  end

  def take_money_from_loser(loser, wager)
    new_amount = loser.money - wager
    new_amount = 1 if new_amount <= 0
    loser.update_attribute(:money, new_amount)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => :login
  before_filter :redirect_if_logged_in, :only => :login

  def index
    @user = current_user
    @message = flash[:message]
  end

  def create
    @user = User.create!(name: params[:user][:name])
    redirect_to :users
  end

  def find_opponent
    @user = User.find(params[:user_id])
    @user.update_attribute(:available, false)
    tier = @user.tier_preference
    
    if @game = @user.waiting_game
      go_to(@game)
    elsif @opponent = @user.snatch_opponent(tier)
      @game = Game.create!(initiator: @user, opponent: @opponent, wager: tier)
      @game.players.create!(user: @user)
      @game.players.create!(user: @opponent)
      redirect_to @game
    else
      flash[:message] = "No other users are currently available. Try changing your wager or try again later."
      redirect_to :users
    end
  end

  def become_searchable
    user = User.find(params[:user_id])
    tier = params[:selected_tier]
    user.update_attributes(available: true, tier_preference: tier)
  end

private 

  def go_to(game)
    game.update_attribute(:opponent_ready, true)
    PrivatePub.publish_to(ready_game_path(game), "window.location.reload();")
    redirect_to game
  end
  
  def redirect_if_logged_in
    if current_user
      redirect_to root_path
    end
  end
end

app/views/users/_user.html.erb
<li id="<%= user.id %>">
  <%= link_to user.name, new_game_path(opponent_id: user.id) %>
  <%= "<span class='already-played'> - played #{time_ago_in_words(played_user_on)} ago.</span>".html_safe if played_user_on %>
</li>

app/views/users/become_searchable.js.erb
// don't remove this file or you get a template missing error

app/views/users/index.html.erb
<div id="sign-out">
  Hi, <%= @current_user.first_name %>
  <%= link_to "Sign out", signout_path %>
</div>

<div id="funds">
  You have: <b><%= money_to_s(@current_user.money) %></b>
</div>

<div id="select-player">
  <%= form_tag({action: :find_opponent}, id: "find-opponent") do %>
    <%= label_tag :tier, "Play for" %>
    <% if @current_user.tier_options.size == 1 %>
      <%= money_to_s(@current_user.tier_options.first) %>
      <%= hidden_field_tag :tier, @current_user.tier_options.first %>
    <% else %>
      <%= select_tag :tier, options_for_select(
            @current_user.tier_options.map{|i| [money_to_s(i), i] }, 
            @current_user.tier_preference) %>
    <% end %>
    <%= hidden_field_tag :user_id, @current_user.id %>
    <%= submit_tag "", class: "hidden" %>
  <% end %>

  <%= form_tag({action: :become_searchable}, remote: true) do %>
    <%= hidden_field_tag :user_id, @current_user.id %>
    <%= hidden_field_tag :selected_tier, @current_user.tier_preference %>
    <%= submit_tag "Find Opponent", id: 'become-available' %>
  <% end %>
</div>

<div id="home-message">
  <%= @message %>
</div>

<div id="finding-player-overlay">
  <div>Finding Opponent...</div>
  <%= image_tag "inner-ring.png", class: 'spinning-ring', id: 'inner-ring' %>
  <%= image_tag "outer-ring.png", class: 'spinning-ring', id: 'outer-ring' %>
</div>

app/views/users/login.html.erb
<div>
  <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
</div>

app/views/users/new.html.erb
<div id="enter-name">
  Enter your name:

  <%= form_for User.new do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "Play!" %>
  <% end %>
</div>

app/views/users/update_availability.js.erb
// don't remove this