config/routes.rb
Dash::Application.routes.draw do
  get "sessions/create"
  get "sessions/destroy"
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'login', to: 'users#login'

  root to: 'users#index'

  resources :sessions, only: [:create, :destroy]

  resources :users do
    collection do
      post :become_searchable
      post :find_opponent
      post :available_members
    end
  end

  resources :games do
    member do
      post :play
      post :ready
      post :action
      post :opponent_ready
      delete :play
    end
  end

  resources :players do
    member do
      post :action
    end
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  ACTIONS = {
    move:   'Move 1 Space',
    roll:   'Roll Die',
    defend: 'Defend',
    base:   'Move Base',
    trap:   'Place Trap'
  }

  include ActionView::Helpers::TextHelper

  has_many   :players
  has_many   :rounds
  has_many   :actions, through: :rounds

  belongs_to :initiator, class_name: 'User'
  belongs_to :opponent,  class_name: 'User'
  belongs_to :winner,    class_name: 'User'

  def player(current_user)
    players.reject{ |player| player.user_id == current_user.id }.first
  end

  def opponent(current_user)
    players.select{ |player| player.user_id == current_user.id }.first
  end

  def current_round
    rounds.last
  end

  def players_ready?
    players.all?(&:ready)
  end

  def started?
    players_ready?
  end

  def no_rounds?
    rounds.size == 0
  end

  def new_round?
    rounds.size == 0 ||
    current_round.complete?
  end

  def has_user?(user)
    players.map(&:user).include?(user)
  end

  def has_two_players?
    players.size == 2
  end

  def active?
    !winner
  end

  def set_winner(winner:, loser:)
    update_attribute(:winner, winner.user)
    winner.user.transfer_money(loser.user, wager)
  end

  def wager_to_s
    pluralize(wager, 'cent')
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    initiator = User.find(params[:user_id])
    opponent = User.find(params[:opponent_id])
    
    @game = Game.create!(initiator: initiator, opponent: opponent, wager: initiator.money)
    @player = @game.players.create!(user: initiator)
    @opponent = @game.players.create!(user: opponent)

    PrivatePub.publish_to("/games/new", 
      game: @game, 
      url: game_path(@game), 
      initiator_name: initiator.name, 
      initiator_id: initiator.id,
      opponent_id: opponent.id
    )

    render :show
  end

  def show
    @game = Game.find_by(id: params[:id])

    if @game && @game.has_user?(current_user) && @game.active? && @game.has_two_players?
      @player   = @game.player(current_user)
      @opponent = @game.opponent(current_user)
      @actions  = Game::ACTIONS
      unless Rails.env.production?
        @actions[:reset] = "Reset"
        @actions[:win] = "Win"
      end
    else
      binding.pry
      redirect_to :root
    end
  end

  def ready
    player_id = params[:data][:player_id]
    game_id   = params[:data][:game_id]
    game      = Game.find(game_id)

    Player.find(player_id).update_attribute(:ready, true)

    if game.players_ready?
      PrivatePub.publish_to(action_game_path(game_id), "window.beginRound();")
    else
      PrivatePub.publish_to(action_player_path(player_id), "window.playerReady();")
    end
  end

  def play
    action        = params[:move]
    game          = Game.find(params[:id])
    player        = Player.find(params[:playerId])
    opponent      = Player.find(params[:opponentId])

    if game.new_round?
      round = game.rounds.create!(first_player: player)
      player.actions.create!(round: round, action: action)
    else
      round = game.current_round
      # game/play is getting called twice sometimes. PorqUe wHy?
      return if round.first_player == player
      round.update_attributes(second_player: player)
      player.actions.create!(round: round, action: action)
      players = [player, opponent]

      players.each_with_index do |player, index|
        halt_gameplay = false

        p_action      = player.action(round).action
        message       = ""
        javascript    = ""

        opponent      = (players - [player]).first
        o_action      = opponent.action(round).action
        o_javascript  = ""

        case p_action 
        when "move"
          player.update_attribute(:position, player.position + 1)

        when "roll"
          roll = rand(1..6)
          roll = (13 - player.position) if (player.position + roll) > 13

          old_position = player.position
          traps        = opponent.active_traps
          skipped_trap = player.skipped_trap(roll, old_position, traps)

          if o_action == "defend"
            new_position = player.base_position
            message += "#{opponent.name} defended!" 
          elsif skipped_trap.present?
            skipped_trap.update_attribute(:active, false)
            new_position = player.base_position
            message += "You hit a trap!"
            o_javascript += "window.removeTrap(#{opponent.id}, #{skipped_trap.position});"
          else
            new_position = (player.position + roll)
            message += "You rolled a #{roll}."
          end

          player.update_attribute(:position, new_position)

        when "base"
          if player.can_move_base?
            player.base_positions.create!(position: player.position)
            javascript += "window.base(#{player.id}, #{player.position});"
          else
            message += "You cannot place a trap there."
          end

        when "trap"
          if player.can_place_trap?
            player.traps.create!(position: player.position)
            javascript += "window.traps(#{player.id}, #{player.position});"
          else
            message += "You cannot place a trap there."
          end

        when "fail"
          message += "Choose an option before the time runs out!"

        when "reset"
          [player, opponent].each do |p|
            p.traps.each{|trap| trap.update_attribute(:active, false)}
            p.base_positions.each(&:destroy)
            javascript += "window.baseReset(#{p.id}, #{p.position});" +
                          "window.trapsReset(#{p.id}, #{p.position});"
          end
        when "win"
          player.update_attribute(:position, 13)
        end

        javascript   += "window.move(#{player.id}, #{player.position}); window.notice('#{message}');"+
                        "window.disableButtons(#{player.position}, #{player.base_position})"
        o_javascript += "window.move(#{player.id}, #{player.position});"

        PrivatePub.publish_to(action_player_path(player.id), javascript)
        PrivatePub.publish_to(action_player_path(opponent.id), o_javascript)

        if index == 1
          if player.position < 13 && opponent.position < 13
            PrivatePub.publish_to(action_game_path(game.id), "window.restartRound();")
          else
            if player.position >= 13
              p_alert = "You won #{game.wager_to_s}!!!!".upcase
              o_alert = "You lost #{game.wager_to_s}."
              game.set_winner(winner: player, loser: opponent)
              if opponent.position >= 13
                p_alert = "It was a TIE!"
                o_alert = "It was a TIE!"
              end
            elsif opponent.position >= 13
              p_alert = "You lost #{game.wager_to_s}."
              o_alert = "You won #{game.wager_to_s}!!!".upcase
              game.set_winner(winner: opponent, loser: player)
            end

            halt_gameplay = true

            javascript   = "alert('#{p_alert}'); window.location.replace('#{ root_path }');"
            o_javascript = "alert('#{o_alert}'); window.location.replace('#{ root_path }');"

            PrivatePub.publish_to(action_player_path(player.id), javascript)
            PrivatePub.publish_to(action_player_path(opponent.id), o_javascript)
          end
        end
      end
    end
  end

  def opponent_ready
    @game = Game.find(params[:game_id])
    @initiator = User.find params[:initiator_id]
    @opponent  = User.find params[:opponent_id]

    if params[:answer] == "true"
      @game.update_attribute(:opponent_accepted, true)

      PrivatePub.publish_to("/games/opponent_decision/#{@game.id}", 
        "window.location.reload();"
      )
      render text: game_path(@game)

    else
      @game.destroy

      @initiator.update_availability(true)
      @opponent.update_availability(true)

      PrivatePub.publish_to("/games/opponent_decision/#{@game.id}", 
        "window.location.replace('#{users_path}');"
      )
    end
  end

end

app/views/games/_instructions.html.erb
<div id="instructions-overlay">
  <div id="instructions">
    <p>The goal is to make it to your opponent's side before they get to yours</p>
    <p>You'll have 7 seconds to choose an option. Pick quickly!</p>
    <p>You'll figure it out. Good luck!</p>
    <!-- countdown from 10 -->
    <%= button_to "Ready?", ready_game_path(game, data: { player_id: them.id, game_id: game.id  }), 
                  method: "POST", remote: true, class: 'ready-button' %>
  </div>
  <div id="waiting">
    <%= image_tag "loading-white.gif", class: 'loading-gif no-padding' %>
    <span class="waiting-message">Waiting for opponent...</span>
  </div>
</div>

app/views/games/_waiting.html.erb
<div id="loading-container">
  <%= image_tag 'loading.gif', class: 'loading-gif' %>
  <span class="waiting-message">Waiting for opponent...</span>
</div>
<%= subscribe_to "/games/opponent_ready/#{@game.id}" %>

app/views/games/edit.html.erb
Waiting for opponent to confirm.

Please wait...

<%= subscribe_to edit_game_path(@game) %>

app/views/games/play.js.erb
// don't remove this file or you get a template missing error

app/views/games/show.html.erb
<%= javascript_include_tag params[:controller] %>
<%= subscribe_to action_game_path(@game.id) %>
<%= subscribe_to ready_game_path(@game.id) %>
<%= subscribe_to action_player_path(@opponent.id) %>

<div id="them-name-container">
  <strong id="them-name" data-id="<%= @player.id %>">
    <%= @opponent.name %>
  </strong>
</div>

<div id="wager">
  <%= money_to_s(@game.wager) %>
</div>

<div id="gameplay">
  <% if @game.opponent_ready %>
    <div id="notice"></div>
    <div class="left" id="field-portion">
      <table id="field">
        <tr class="base them-base">
          <td class="them-field" id="<%= @player.id %>_0"></td>
          <td class="you-field" id="<%= @opponent.id %>_13"></td>
        </tr>
        
        <% 12.times do |n| %>
          <tr class="battle-fields">
            <td class="field them-field" id="<%= @player.id %>_<%= n + 1 %>"></td>
            <td class="field you-field" id="<%= @opponent.id %>_<%= 12 - n %>"></td>
          </tr>
        <% end %>

        <tr class="base you-base">
          <td class="them-field" id="<%= @player.id %>_13"></td>
          <td class="you-field" id="<%= @opponent.id %>_0"></td>
        </tr>
      </table>
    </div>
    <div class="right">
      <div id="timer-display"></div>
      <div id="action-portion">
        <% @actions.each do |action, name| %>
          <button id="<%= action %>" 
                  data-played-by="<%= @opponent.id %>"
                  data-played-on="<%= @player.id %>"
                  data-game-id="<%= @game.id %>"
                  class="action-button">
            <%= name %>
          </button>
        <% end %>
      </div>
    </div>
    <% unless @game.started? %>
      <%= render partial: 'instructions', locals: { game: @game, them: @opponent } %>
    <% end %>
  <% else %>
    <%= render partial: 'waiting' %>
  <% end %>

</div>

<div id="you-name-container">
  <strong id="you-name" data-id="<%= @player.id %>">
    <%= @player.name %>
  </strong>
</div>

<% if @game.opponent_ready? %>
  <script>
    <% @opponent.active_traps.each do |trap| %>
      window.traps(<%= @opponent.id %>, <%= trap.position %>);
    <% end %>

    window.base(<%= @opponent.id %>, <%= @opponent.base_position %>);

    <% [@opponent, @player].each do |player| %>
      window.move(<%= player.id %>, <%= player.position %>);
    <% end %>

    window.disableButtons(<%= @player.position %>, <%= @player.base_position %>);
    window.bindButtons();
  </script>
<% end %>